### ISSUE TITLE
please change notifications

### ISSUE THREAD

**Issue by cordoval** [BranchBit/AuditLogBundle#1]
i think you are spamming a lot of people with this notfications unchagned from FOS bundle

**Comment by whitewhidow** [comment]
im sorry im not following ??  am i doing something wrong here ?

**Comment by cordoval** [comment]
for some reason on travis you are spamming with notifications

**Comment by whitewhidow** [comment]
im so sorry man, i had no idea. My apologies to everyone that i have spammed ...

**Comment by whitewhidow** [comment]
i've removed the notification from .travis.yml 

9b25e725066361a3363d63b21d5f009c5d8a98e0

**Comment by cordoval** [comment]
is ok, thanks, no worries, :+1:

**Comment by cordoval** [comment]
remember, it is oke :blush:

**Comment by whitewhidow** [comment]
:+1:
